baseURL = "/"
languageCode = "en-gb"
title = "Rusty.Pro"

theme = "hello-friend"
Paginate = 5

[permalinks]
  posts = "/:year/:slug/"

[taxonomies]
  tag = "tags"

[params]
  contentTypeName = "posts"
  showReadingTime = true
  rssFullText = true
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Rusty.Pro"
    subtitle = "(noun) - an out of practice sysadmin"
    dateFormatSingle = "02 January 2006"
    dateFormatList = "02 January 2006"

    [languages.en.params.logo]
      logoText = "Rusty.Pro"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"

      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"