baseURL = "https://rusty.pro"
languageCode = "en-gb"
title = "Rusty.Pro"

theme = "kiss"
disqusShortname = "rusty-pro"
Paginate = 5

[permalinks]
  post = "/:slug/"

[taxonomies]
  tag = "tags"

[blackfriday]
  hrefTargetBlank = true

[params.info]
  homeTitle = "Rusty.Pro ⇒ (noun) - an out of practice sysadmin"

[params.features]
  disqusOnDemand = true

[params.social]
  twitter = "_rustypro"
  github = "russparsloe"
  linkedin = "russparsloe"
  email = "hello@rusty.pro"

[params.social.config]
  platforms = [ "twitter", "github", "linkedin", "email" ]
